#!/bin/bash

ibrun $HOME/CharLES/nextgen_turb/charles.exe -i 03_charles.in | tee log.test

# $HOME/nextgen/bin/surfer.exe -i 01_surfer.in 
#mpiexec -n 680 $HOME/nextgen/bin/stitch.exe -i 02_stitch.in
