#!/bin/bash

ibrun $HOME/CharLES/nextgen_turb/charles.exe -i 00_post_test.in | tee log.post_test
# ibrun $HOME/CharLES/nextgen_turb/charles.exe -i 00_post_avg.in | tee log.post

# $HOME/nextgen/bin/surfer.exe -i 01_surfer.in 
#mpiexec -n 680 $HOME/nextgen/bin/stitch.exe -i 02_stitch.in
