#!/bin/bash
nNodes=1
# nCores=$((68*$nNodes))
nCores=$((12*$nNodes))

fInput='03_charles_init.in'
fLog='log.init'

# mpiexec -n $nCores $HOME/nextgen_turb/charles.exe -i $fInput | tee $fLog
mpiexec -n $nCores /home/yunjaeh/CharLES/nextgen_turb/charles.exe -i $fInput | tee $fLog

