#!/bin/bash
nNodes=1
# nCores=$((68*$nNodes))
nCores=$((12*$nNodes))

fInput='00_post.in'
fLog='log.post'

mpiexec -n $nCores /home/yunjaeh/CharLES/nextgen_turb/charles.exe -i $fInput | tee $fLog

$HOME/CharLES/nextgen/bin/ping_s.exe --IMAGES ./output_stat/*.png --DUMP_DATA ./output_stat/txt/


